### PR TITLE
fix: use import id @prisma/client by default when possible

### LINKED ISSUE #76: DMMF dynamic require causing MODULE_NOT_FOUND
#### Screenshot

Screenshot from 2021-06-04 14-57-04

#### Description

`nexus-prisma` returns a "MODULE_NOT_FOUND" error when calling the function that fetches the DMMF.

It looks like the dynamic require here is throwing the error:

https://github.com/prisma/nexus-prisma/blob/acfdc6b08f84a0c752ec0edc8cc251c81302294f/src/helpers/prisma.ts#L14-L23

When I modify the variable `importId` for its default value '@prisma/client' directly in the require like so `require('@prisma/client')` it works correctly. So with that in mind I've tried a few "hack" such as trying to wrap the variable in a template literals ``require(`${importId}`)`` as well as appending an empty string `require('' + importId)` but both still returned the error. 

#### Possible solutions

Integrate the require code within the generated file /  generate the prisma helper file with the `require` pointing directly to the package name's string instead of using a variable at runtime?

Use dynamic `import` instead of `require`?

#### Repro Steps

https://github.com/haleksandre/nexus-prisma-test

```bash
git clone https://github.com/haleksandre/nexus-prisma-test.git
cd nexus-prisma-test

npm install
npm run build
node dist/server.js
```

### PR DESCRIPTION
**Pull request by jasonkuhrt**
closes #76 

#### TODO

- [x] tests

### CODE REVIEW

File: src/cli/nexus-prisma.ts [hunk 1]
```diff
@@ -44,3 +51,78 @@ generatorHandler({
     )
   },
 })
+
+/**
+ * Hehlpers
```
Comment (iddan) [inline src/cli/nexus-prisma.ts:56]:
```suggestion
 * Helpers
```

Comment (jasonkuhrt) [reply src/cli/nexus-prisma.ts:56]: ty!
